docker buildx includes automated push to...
eclipse/che-machine-exec pull request #125
Opened 2021-01-28 21:20 UTC by nickboldt

### What does this PR do?

docker buildx includes automated push to registry, so build using tag we want published; also since there's no point in tagging the image with a SHA tag and a version tag, simplify things

Change-Id: I56fd67698fe4f9b36099c9dd9bd438f18a2fba05
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit messasge above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

2021-01-28 21:45 UTC, benoitf approved these changes

2021-01-29 12:03 UTC, AndrienkoAleksandr approved these changes

2021-01-29 12:54 UTC, mkuznyetsov requested changes

2021-01-29 12:54 UTC, mkuznyetsov commented on make-release.sh
> +    -f ./${DOCKERFILE} . --platform "linux/amd64,linux/ppc64le,linux/s390x" | cat
it also needs `--push` parameter, in order to perform actual push

2021-01-29 13:33 UTC, mkuznyetsov approved these changes

2021-01-29 13:36 UTC, merged